version: '3.5'
services:
  nginx:
    image: nginx:1.17.4
    ports:
      - '81:80'

    depends_on:
      - php
      - mysql
      - npm
    volumes:
      - ./backend:/var/www/html
      - ./nginix-default.conf:/etc/nginx/conf.d/default.conf
    

  php:
    build: 
        context: .
        dockerfile: Dockerfile
    volumes: 
        - ./backend:/var/www/html
    ports: 
        - '9001:9000'
    
    depends_on:
      - mysql
      - redis

  mysql:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    ports: 
        - '3307:3306'
    environment:
      - MYSQL_DATABASE=project
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=hoangpham
      - MYSQL_PASSWORD=password
      - SERVICE_TAGS=dev
      - SERVICE_NAME=mysql
    
    
  redis:
    image: redis:latest
    ports:
      - "6378:6379"


  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - '8181:80'
    environment:
      - PMA_HOST=mysql

  composer:
    image: composer:latest
    volumes:
      - ./backend:/var/www/html
    working_dir: /var/www/html
    command: ["composer", "install"]
    
  npm:
    
    build: 
      dockerfile: ./demo/Dockerfile
    volumes: 
        - ./demo/:/home/node/app
    ports: 
      - '3333:3000'
    command: ["npm run dev"]
    
 
